### ISSUE TITLE
Can you provide source code/build instructions?

### ISSUE THREAD

**Issue by telent** [koendv/blackmagic-blackpill#1]
The source code in the Releases tab isn't actually BMP source code, just the sources for this repo. Is this built from the blacksphere repo? Would be awesome if you could provide details

The binaries you've uploaded don't work on my  stm32f401 - I don't know if that's because of differences in the model or if I've got a duff device or if I'm doing it wrong,

**Comment by koendv** [comment]
I just tested; binary works fine on a WeAct F411 "black pill". 

This is how the binary is built:

For WeAct stm32f411 black pill:
```
git clone https://github.com/kdv-temp/blackmagic/
cd blackmagic
patch -p1 < ../led.patch
make PROBE_HOST=f4discovery BLACKPILL=1 ENABLE_RTT=1
```
For stm32f4discovery:
```
git clone https://github.com/kdv-temp/blackmagic/
cd blackmagic
make PROBE_HOST=f4discovery ENABLE_RTT=1
```
I've added a zip with binaries for weact and f4discovery.
Can you provide me more information about your board, and the way you upload the binary?
[binaries.zip](https://github.com/koendv/blackmagic-blackpill/files/7666077/binaries.zip)

**Comment by telent** [comment]
Thanks!

The board was advertised as a Blackpill and looks like a blackpill, but looking at it closely I think it's a clone  - doesn't have the WeAct logo printed on it. The chip markings are

```
STM32F
401CCU6
GH27 VQ
CHN 103
```

I put it in DFU mode by pressing NRST while holding BOOT0 down, then it enumerates as 

    Bus 001 Device 094: ID 0483:df11 STMicroelectronics STM Device in DFU Mode

then I run 

    $ sudo dfu-util -a 0 --dfuse-address 0x08000000  -D blackmagic.bin 

then when it's done I press NRST and it disappears as a USB device. Kernel log says

    [415477.334420] usb 1-1: USB disconnect, device number 94

The red LED remains lit throughout, I don't ever see the blue (C13?) light

I don't believe it's a cable problem  - I tried re-uploading the downloaded firmware with the -U flag and that is identical.

It doesn't work with the weact binary from your zip, I don't know if there are relevant changes between 401 and 411 that would require source changes.

Not sure what to try next. I'm going to try rebuilding from your repo, but I don't anticipate it'll do anything different from the binary you provided.  I have ordered an ST-LINK (which I will need anyway if I can't get this to work), maybe when that arrives I can use it to find out what's going on

**Comment by koendv** [comment]
This is my kernel log:

[22730.352185] usb 1-1.3: new full-speed USB device number 17 using xhci_hcd
[22730.464266] usb 1-1.3: New USB device found, idVendor=1d50, idProduct=6018, bcdDevice= 1.00
[22730.464275] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[22730.464281] usb 1-1.3: Product: Black Magic Probe (F4Discovery/BlackPillV2) v1.7.1-332-ga703a79-dirty
[22730.464286] usb 1-1.3: Manufacturer: Black Sphere Technologies
[22730.464291] usb 1-1.3: SerialNumber: 338138443430
[22730.470445] cdc_acm 1-1.3:1.0: ttyACM1: USB ACM device
[22730.476710] cdc_acm 1-1.3:1.2: ttyACM2: USB ACM device

If you don't see the two tty's, there's a problem.

**Comment by telent** [comment]
I seem to have got it working eventually, though I have no idea how. It doesn't seem as though any of these changes should make a differece

https://gist.github.com/telent/d760d4f3e9b79feed8d5020fc21d7fef

Now I have 

```
Bus 001 Device 009: ID 1d50:6018 OpenMoko, Inc. Black Magic Debug Probe (Application)


[433282.402193] usb 1-3: New USB device found, idVendor=1d50, idProduct=6018, bcdDevice= 1.00
[433282.402200] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[433282.402204] usb 1-3: Product: Black Magic Probe (F4Discovery/BlackPillV2) 123456
[433282.402207] usb 1-3: Manufacturer: Black Sphere Technologies
[433282.402210] usb 1-3: SerialNumber: 379D388C3034
[433282.405496] cdc_acm 1-3:1.0: ttyACM0: USB ACM device
[433282.406473] cdc_acm 1-3:1.2: ttyACM1: USB ACM device
```

Maybe in the morning this will make more sense

**Comment by Uberi** [comment]
This thread was really helpful in getting things up and running with an STM32F401CC Black Pill! I wanted to share some findings:

* There are at least 3 different WeAct "Black Pill" boards in the wild: [v1.2](https://stm32-base.org/boards/STM32F401CCU6-WeAct-Black-Pill-V1.2.html) uses an STM32F401CCU6, [v2](https://stm32-base.org/boards/STM32F411CEU6-WeAct-Black-Pill-V2.0.html) uses an STM32F411CEU6, and [v3](https://stm32-base.org/boards/STM32F401CEU6-WeAct-Black-Pill-V3.0) uses an STM32F401CEU6.
* There are also a bunch of other boards that are also called "Black Pill", some of which can be found by searching within this page: https://stm32-base.org/boards/.
* According to the diagram on their website: https://www.st.com/en/microcontrollers-microprocessors/stm32f401.html, the STM32F401 comes with configurations from 128kB flash/64kB RAM all the way up to 512kB flash/96kB RAM.
* According to the diagram on their website: https://www.st.com/en/microcontrollers-microprocessors/stm32f411.html, the STM32F411 comes with configurations from 256kB flash/128kB RAM all the way up to 512kB flash/128kB RAM.

I tested @telent's patch, which was extremely helpful for debugging, and reduced it to this smaller patch:

```patch
diff --git a/src/platforms/stm32/blackpillv2.ld b/src/platforms/stm32/blackpillv2.ld
index 4dbc774..60a04ad 100644
--- a/src/platforms/stm32/blackpillv2.ld
+++ b/src/platforms/stm32/blackpillv2.ld
@@ -20,8 +20,8 @@
 /* Define memory regions. */
 MEMORY
 {
-	rom (rx) : ORIGIN = 0x08000000, LENGTH = 512K
-	ram (rwx) : ORIGIN = 0x20000000, LENGTH = 96K
+	rom (rx) : ORIGIN = 0x08000000, LENGTH = 256K
+	ram (rwx) : ORIGIN = 0x20000000, LENGTH = 64K
 }
 
 /* Include the common ld script from libopenstm32. */
```

That means the memory regions were too large for the STM32F401CC I had (Black Pill v1.2), but perfectly sized for a STM32F401CE (Black Pill v3.0). I tested building the firmware with an even smaller setting, and this worked too:

```patch
diff --git a/src/platforms/stm32/blackpillv2.ld b/src/platforms/stm32/blackpillv2.ld
index 4dbc774..60a04ad 100644
--- a/src/platforms/stm32/blackpillv2.ld
+++ b/src/platforms/stm32/blackpillv2.ld
@@ -20,8 +20,8 @@
 /* Define memory regions. */
 MEMORY
 {
-	rom (rx) : ORIGIN = 0x08000000, LENGTH = 512K
-	ram (rwx) : ORIGIN = 0x20000000, LENGTH = 96K
+	rom (rx) : ORIGIN = 0x08000000, LENGTH = 128K
+	ram (rwx) : ORIGIN = 0x20000000, LENGTH = 64K
 }
 
 /* Include the common ld script from libopenstm32. */
```

This is the smallest possible STM32F4 variant, 128kB flash/64kB RAM, which I think means that it'll work on every STM32F4 variant, not just the WeAct Black Pill v3.0!

@koendv, would you consider a PR with the following changes?

* Add details in the README.md about the various models of Black Pill out there.
* New patch, `blackpill.patch`, that includes the 128kB flash/64kB RAM changes mentioned above.
* Add build instructions to README_DEVELOPER.md about using that patch.

**Comment by koendv** [comment]
OK. I have added a binary for stm32f401cc. Can you test the binary works?
I have chosen not to add a binary for stm32f4 with 128 kbyte flash. 
This is why:

```
bytes  |command
116912 | make PROBE_HOST=f4discovery BLACKPILL=1
121372 | make PROBE_HOST=f4discovery BLACKPILL=1 ENABLE_RTT=1
156728 | make PROBE_HOST=f4discovery BLACKPILL=1 ENABLE_RTT=1 ENABLE_DEBUG=1
```
IMHO, it is better to have 256kbyte flash and know that everything fits, no matter what features you need.

**Comment by Uberi** [comment]
Works great, thanks for the update :)

**Comment by ankostis** [comment]
Great, thanks, your `README_DEVELOPER.md` instructions worked thet 1st like charm.

But why don't you integrate them into a proper repo fork,
or even better, proper a merge-request into blackmagic-debug/blackmagic repo?
